import { compactVietnameseMulti } from "./core/vietnamese-prompt-expert.js";
import { installPromptCopyGuard } from "./core/prompt-copy-guard.js";
import {compileMultiShot,compileMultiView,SHOT_ANGLES,EXPERT09_ZONES} from "./core/multishot-engine.js";
const $=id=>document.getElementById(id);
let masterUrl=null;
let selectedAITarget="ChatGPT Images";
const aiTargetButtons=[...document.querySelectorAll(".ai-target-option")];
for(const button of aiTargetButtons){button.addEventListener("click",()=>{selectedAITarget=button.dataset.aiTarget;for(const item of aiTargetButtons){const active=item===button;item.classList.toggle("active",active);item.setAttribute("aria-pressed",String(active));}$("customAiLabel").hidden=selectedAITarget!=="Khác";});}

$("master").addEventListener("change",()=>{if(masterUrl)URL.revokeObjectURL(masterUrl);const f=$("master").files[0];$("output").value="";$("status").textContent="";masterUrl=f?URL.createObjectURL(f):null;$("masterPreview").style.display=f?"block":"none";if(f)$("masterPreview").src=masterUrl;});
$("bodySuggest").addEventListener("click",()=>{$("bodyText").value="Adult person with naturally balanced proportions, relaxed shoulders and realistic posture. Preserve believable anatomy without exaggeration.";});
const landscapeCasts=new Set(["pedestrians","visitors","family","cyclists","gardeners","community","crowd","custom"]);function syncCast(){const architecture=$("space").value==="architecture";const cast=$("cast");for(const opt of cast.options){if(landscapeCasts.has(opt.value))opt.hidden=!architecture;}if(!architecture&&landscapeCasts.has(cast.value))cast.value="auto";$("castNoteLabel").hidden=!architecture||cast.value!=="custom";} $("space").addEventListener("change",syncCast);$("cast").addEventListener("change",syncCast);syncCast();
function syncZones(){const select=$("zone");const old=select.value;select.replaceChildren();for(const [value,label] of Object.entries(EXPERT09_ZONES[$("space").value])){const opt=document.createElement("option");opt.value=value;opt.textContent=label;select.append(opt);}select.value=Object.hasOwn(EXPERT09_ZONES[$("space").value],old)?old:"auto";$("zoneNote").placeholder=$("space").value==="architecture"?"Ví dụ: lối đi giữa vườn, sân trong phía đông":"Ví dụ: sofa cạnh cửa kính, hệ tủ trưng bày";} $("space").addEventListener("change",()=>{syncZones();document.querySelectorAll(".shotZone").forEach(sel=>{const old=sel.value;sel.replaceChildren();for(const [value,label] of Object.entries(EXPERT09_ZONES[$("space").value])){const opt=document.createElement("option");opt.value=value;opt.textContent=label;sel.append(opt);}sel.value=Object.hasOwn(EXPERT09_ZONES[$("space").value],old)?old:"auto";});});syncZones();
function count(){return $("outputMode").value==="multiview"?Number($("viewCount").value):{"2x2":4,"3x2":6,"3x3":9}[$("layout").value];}
function syncMode(){const multi=$("outputMode").value==="multiview";$("layoutLabel").style.display=multi?"none":"";$("viewCountLabel").style.display=multi?"":"none";while(document.querySelectorAll(".shot").length>count())document.querySelector(".shot:last-child")?.remove();if(multi){while(document.querySelectorAll(".shot").length<count())addShot();}updateShotUI();}
$("outputMode").addEventListener("change",syncMode);$("viewCount").addEventListener("change",syncMode);syncMode();
function updateShotUI(){const multi=$("outputMode").value==="multiview";$("addShot").hidden=multi;$("shotHelp").textContent=multi?"Mỗi khung tương ứng một ảnh riêng. Chọn thủ công hoặc AI đề xuất cho từng khung.":"Các khung chưa chỉ định sẽ do AI đề xuất.";[...document.querySelectorAll(".shot")].forEach((el,i)=>{el.querySelector(".shothead strong").textContent="SHOT "+String(i+1).padStart(2,"0");el.querySelector(".remove").hidden=multi;});}
function addShot(){if(document.querySelectorAll(".shot").length>=count()){ $("status").textContent="Đã đạt số góc tối đa của bố cục."; return; }const div=document.createElement("div");div.className="shot";div.innerHTML='<div class="shothead"><strong>SHOT · TÙY CHỌN</strong><button type="button" class="secondary remove">Xóa</button></div><label>Quyết định góc nhìn<select class="shotMode"><option value="auto" selected>AI tự đề xuất</option><option value="manual">Kiến trúc sư lựa chọn</option></select></label><div class="shotDetails"><div class="two"><label>Góc máy<select class="angle"></select></label><label>Nhân vật<select class="person"><option value="auto">Theo thiết lập chung</option><option value="none">Không có</option><option value="male">Nam</option><option value="female">Nữ</option><option value="both">Nam + Nữ</option></select></label></div><label>Khu vực ưu tiên<select class="shotZone"></select></label><label>Khu vực / chủ thể<input class="subject" placeholder="Ví dụ: sofa cạnh cửa sổ"></label><label>Hành động / tư thế<input class="action" placeholder="Ví dụ: nữ ngồi uống trà, nhìn ra cửa sổ"></label><label>Ghi chú riêng<input class="note" placeholder="Hướng nhìn, độ cao, ánh sáng..."></label></div>';const z=div.querySelector(".shotZone");for(const [value,label] of Object.entries(EXPERT09_ZONES[$("space").value])){const opt=document.createElement("option");opt.value=value;opt.textContent=label;z.append(opt);}const sel=div.querySelector(".angle");SHOT_ANGLES.forEach(a=>{const opt=document.createElement("option");opt.value=a;opt.textContent=a;sel.append(opt)});const mode=div.querySelector(".shotMode");const details=div.querySelector(".shotDetails");details.hidden=mode.value==="auto";mode.addEventListener("change",()=>{details.hidden=mode.value==="auto";});div.querySelector(".remove").addEventListener("click",()=>{div.remove();updateShotUI();});$("shots").append(div);updateShotUI();}
$("addShot").addEventListener("click",addShot);
$("layout").addEventListener("change",()=>{while(document.querySelectorAll(".shot").length>count())document.querySelector(".shot:last-child")?.remove();updateShotUI();});
$("generate").addEventListener("click",()=>{try{const f=$("master").files[0];if(!f)throw Error("Cần chọn một ảnh MASTER trước khi tạo prompt.");if(!["image/jpeg","image/png","image/webp"].includes(f.type))throw Error("MASTER chỉ hỗ trợ JPG, PNG hoặc WebP.");const shots=[...document.querySelectorAll(".shot")].map(el=>({zone:el.querySelector(".shotZone").value,mode:el.querySelector(".shotMode").value,angle:el.querySelector(".angle").value,person:el.querySelector(".person").value,subject:el.querySelector(".subject").value.trim(),action:el.querySelector(".action").value.trim(),note:el.querySelector(".note").value.trim()}));const config={aiTarget:selectedAITarget==="Khác"?($("customAi").value.trim()||"Khác"):selectedAITarget,master:f.name,space:$("space").value,layout:$("layout").value,zone:$("zone").value,zoneNote:$("zoneNote").value.trim(),cast:$("cast").value,castNote:$("castNote").value.trim(),face:$("face").files[0]?.name||"",bodyText:$("bodyText").value.trim(),outfit:$("outfit").files[0]?.name||"",shots,brief:$("brief").value.trim(),viewCount:count()};const multi=$("outputMode").value==="multiview";const prompt=multi?compileMultiView(config):compileMultiShot(config);$("output").value=compactVietnameseMulti({...config,outputMode:$("outputMode").value});$("status").textContent=multi?"Đã tạo "+count()+" prompt riêng, mỗi prompt cho một ảnh. Đính kèm cùng MASTER khi chạy từng prompt.":"Đã biên dịch "+count()+" góc trong một ảnh tổng hợp. Gửi kèm MASTER và các ảnh Face/Outfit đã chọn.";}catch(e){$("output").value="";$("status").textContent=e.message;}});
$("copy").addEventListener("click",async()=>{if(!$("output").value)return;try{await navigator.clipboard.writeText($("output").value);$("status").textContent="Đã sao chép prompt."}catch{$("output").select();$("status").textContent="Hãy sao chép phần văn bản đã chọn."}});

installPromptCopyGuard({output:$("output"),copyButton:$("copy"),status:$("status")});
