import {compileMultiShot,compileMultiView,SHOT_ANGLES} from "./core/multishot-engine.js";
const $=id=>document.getElementById(id);
let masterUrl=null;
$("master").addEventListener("change",()=>{if(masterUrl)URL.revokeObjectURL(masterUrl);const f=$("master").files[0];$("output").value="";$("status").textContent="";masterUrl=f?URL.createObjectURL(f):null;$("masterPreview").style.display=f?"block":"none";if(f)$("masterPreview").src=masterUrl;});
$("bodySuggest").addEventListener("click",()=>{$("bodyText").value="Adult person with naturally balanced proportions, relaxed shoulders and realistic posture. Preserve believable anatomy without exaggeration.";});
const landscapeCasts=new Set(["pedestrians","visitors","family","cyclists","gardeners","community","crowd","custom"]);function syncCast(){const architecture=$("space").value==="architecture";const cast=$("cast");for(const opt of cast.options){if(landscapeCasts.has(opt.value))opt.hidden=!architecture;}if(!architecture&&landscapeCasts.has(cast.value))cast.value="auto";$("castNoteLabel").hidden=!architecture||cast.value!=="custom";} $("space").addEventListener("change",syncCast);$("cast").addEventListener("change",syncCast);syncCast();
function count(){return $("outputMode").value==="multiview"?Number($("viewCount").value):{"2x2":4,"3x2":6,"3x3":9}[$("layout").value];}
function syncMode(){const multi=$("outputMode").value==="multiview";$("layoutLabel").style.display=multi?"none":"";$("viewCountLabel").style.display=multi?"":"none";while(document.querySelectorAll(".shot").length>count())document.querySelector(".shot:last-child")?.remove();}
$("outputMode").addEventListener("change",syncMode);$("viewCount").addEventListener("change",syncMode);syncMode();
function addShot(){if(document.querySelectorAll(".shot").length>=count()){ $("status").textContent="Đã đạt số góc tối đa của bố cục."; return; }const div=document.createElement("div");div.className="shot";div.innerHTML='<div class="shothead"><strong>SHOT · TÙY CHỌN</strong><button type="button" class="secondary remove">Xóa</button></div><label>Quyết định góc nhìn<select class="shotMode"><option value="manual">Kiến trúc sư lựa chọn</option><option value="auto">AI tự đề xuất</option></select></label><div class="shotDetails"><div class="two"><label>Góc máy<select class="angle"></select></label><label>Nhân vật<select class="person"><option value="auto">Theo thiết lập chung</option><option value="none">Không có</option><option value="male">Nam</option><option value="female">Nữ</option><option value="both">Nam + Nữ</option></select></label></div><label>Khu vực / chủ thể<input class="subject" placeholder="Ví dụ: sofa cạnh cửa sổ"></label><label>Hành động / tư thế<input class="action" placeholder="Ví dụ: nữ ngồi uống trà, nhìn ra cửa sổ"></label><label>Ghi chú riêng<input class="note" placeholder="Hướng nhìn, độ cao, ánh sáng..."></label></div>';const sel=div.querySelector(".angle");SHOT_ANGLES.forEach(a=>{const opt=document.createElement("option");opt.value=a;opt.textContent=a;sel.append(opt)});const mode=div.querySelector(".shotMode");const details=div.querySelector(".shotDetails");mode.addEventListener("change",()=>{details.hidden=mode.value==="auto";});div.querySelector(".remove").addEventListener("click",()=>div.remove());$("shots").append(div);}
$("addShot").addEventListener("click",addShot);
$("layout").addEventListener("change",()=>{while(document.querySelectorAll(".shot").length>count())document.querySelector(".shot:last-child")?.remove()});
$("generate").addEventListener("click",()=>{try{const f=$("master").files[0];if(!f)throw Error("Cần chọn một ảnh MASTER trước khi tạo prompt.");if(!["image/jpeg","image/png","image/webp"].includes(f.type))throw Error("MASTER chỉ hỗ trợ JPG, PNG hoặc WebP.");const shots=[...document.querySelectorAll(".shot")].map(el=>({mode:el.querySelector(".shotMode").value,angle:el.querySelector(".angle").value,person:el.querySelector(".person").value,subject:el.querySelector(".subject").value.trim(),action:el.querySelector(".action").value.trim(),note:el.querySelector(".note").value.trim()}));const config={master:f.name,space:$("space").value,layout:$("layout").value,zone:$("zone").value,zoneNote:$("zoneNote").value.trim(),cast:$("cast").value,castNote:$("castNote").value.trim(),face:$("face").files[0]?.name||"",bodyText:$("bodyText").value.trim(),outfit:$("outfit").files[0]?.name||"",shots,brief:$("brief").value.trim(),viewCount:count()};const multi=$("outputMode").value==="multiview";const prompt=multi?compileMultiView(config):compileMultiShot(config);$("output").value=prompt;$("status").textContent=multi?"Đã tạo "+count()+" prompt riêng, mỗi prompt cho một ảnh. Đính kèm cùng MASTER khi chạy từng prompt.":"Đã biên dịch "+count()+" góc trong một ảnh tổng hợp. Gửi kèm MASTER và các ảnh Face/Outfit đã chọn.";}catch(e){$("output").value="";$("status").textContent=e.message;}});
$("copy").addEventListener("click",async()=>{if(!$("output").value)return;try{await navigator.clipboard.writeText($("output").value);$("status").textContent="Đã sao chép prompt."}catch{$("output").select();$("status").textContent="Hãy sao chép phần văn bản đã chọn."}});
