import {compileMultiShot,SHOT_ANGLES} from "./core/multishot-engine.js";
const $=id=>document.getElementById(id);
let masterUrl=null;
$("master").addEventListener("change",()=>{if(masterUrl)URL.revokeObjectURL(masterUrl);const f=$("master").files[0];masterUrl=f?URL.createObjectURL(f):null;$("masterPreview").style.display=f?"block":"none";if(f)$("masterPreview").src=masterUrl;});
$("bodySuggest").addEventListener("click",()=>{$("bodyText").value="Adult person with naturally balanced proportions, relaxed shoulders and realistic posture. Preserve believable anatomy without exaggeration.";});
function count(){return {"2x2":4,"3x2":6,"3x3":9}[$("layout").value];}
function addShot(){if(document.querySelectorAll(".shot").length>=count())return;const div=document.createElement("div");div.className="shot";div.innerHTML='<div class="shothead"><strong>SHOT CHỈ ĐỊNH</strong><button type="button" class="secondary remove">Xóa</button></div><div class="two"><label>Góc máy<select class="angle"></select></label><label>Nhân vật<select class="person"><option value="auto">Theo thiết lập chung</option><option value="none">Không có</option><option value="male">Nam</option><option value="female">Nữ</option><option value="both">Nam + Nữ</option></select></label></div><label>Khu vực / chủ thể<input class="subject" placeholder="Ví dụ: sofa cạnh cửa sổ"></label><label>Hành động / tư thế<input class="action" placeholder="Ví dụ: nữ ngồi uống trà, nhìn ra cửa sổ"></label><label>Ghi chú riêng<input class="note" placeholder="Hướng nhìn, độ cao, ánh sáng..."></label>';const sel=div.querySelector(".angle");SHOT_ANGLES.forEach(a=>{const opt=document.createElement("option");opt.value=a;opt.textContent=a;sel.append(opt)});div.querySelector(".remove").addEventListener("click",()=>div.remove());$("shots").append(div);}
$("addShot").addEventListener("click",addShot);
$("layout").addEventListener("change",()=>{while(document.querySelectorAll(".shot").length>count())document.querySelector(".shot:last-child")?.remove()});
$("generate").addEventListener("click",()=>{try{const f=$("master").files[0];if(!f)throw Error("Cần chọn một ảnh MASTER trước khi tạo prompt.");const shots=[...document.querySelectorAll(".shot")].map(el=>({angle:el.querySelector(".angle").value,person:el.querySelector(".person").value,subject:el.querySelector(".subject").value.trim(),action:el.querySelector(".action").value.trim(),note:el.querySelector(".note").value.trim()}));const prompt=compileMultiShot({master:f.name,space:$("space").value,layout:$("layout").value,zone:$("zone").value,zoneNote:$("zoneNote").value.trim(),cast:$("cast").value,face:$("face").files[0]?.name||"",bodyText:$("bodyText").value.trim(),outfit:$("outfit").files[0]?.name||"",shots,brief:$("brief").value.trim()});$("output").value=prompt;$("status").textContent="Đã biên dịch "+count()+" góc trong một ảnh tổng hợp. Gửi kèm MASTER và các ảnh Face/Outfit đã chọn.";}catch(e){$("status").textContent=e.message;}});
$("copy").addEventListener("click",async()=>{if(!$("output").value)return;try{await navigator.clipboard.writeText($("output").value);$("status").textContent="Đã sao chép prompt."}catch{$("output").select();$("status").textContent="Hãy sao chép phần văn bản đã chọn."}});
